imports:
    - { resource: ../default/config.yml }

core:
    require_dev_dependencies: true

    debug:
        exceptions: true
        sql_explain: true

    twig:
        debug: true
        auto_reload: true
        enable_debug_extension: true
